webtalk_init -webtalk_dir D:\\FPGA\\hardware\\Olimex_RGB_Matrix\\matrix_vc\\sdk2\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-11-16 17:10:37" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "s1cabeuqbflm5430jbq7c8c35v" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.055 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1542383939143" -context "sdk\\\\bsp/1542383939143"
webtalk_add_data -client sdk -key hwid -value "1542372685714" -context "sdk\\\\bsp/1542383939143"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1542383939143"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1542383939143"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1542383939143"
webtalk_add_data -client sdk -key uid -value "1542383944186" -context "sdk\\\\application/1542383944186"
webtalk_add_data -client sdk -key hwid -value "1542372685714" -context "sdk\\\\application/1542383944186"
webtalk_add_data -client sdk -key bspid -value "1542383939143" -context "sdk\\\\application/1542383944186"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1542383944186"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1542383944186"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1542383944186"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1542383944186"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1542383944186"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1542383944186"
webtalk_add_data -client sdk -key projSize -value "299.35546875" -context "sdk\\\\application/1542383944186"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1542384637819"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1542384637819"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1542384637819"
webtalk_add_data -client sdk -key DebugCount -value "10" -context "sdk\\\\bsp/1542384637819"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1542384637819"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1542384637819"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1542384637819"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1542384637819"
webtalk_transmit -clientid 2501182495 -regid "" -xml D:\\FPGA\\hardware\\Olimex_RGB_Matrix\\matrix_vc\\sdk2\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\FPGA\\hardware\\Olimex_RGB_Matrix\\matrix_vc\\sdk2\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\FPGA\\hardware\\Olimex_RGB_Matrix\\matrix_vc\\sdk2\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
